languaje: python
python:
  - "2.7"
install:
  "pip install -r requerimientos.txt"

before_script:
  - autopep8 -ir *
  - flake8 --max-complexity=5 --exclude=*.txt,*.md,*.pyc *

script:
  python bdd/tests/features/CalculadoraTest.py
  coverage run --branch bdd/tests/features/CalculadoraTest.py
  lettuce bdd/tests/